name: "Federated Container Action"
description: "Builds a federated container"
branding:
  icon: "check-square"
  color: "blue"
inputs:
  exposes:
    description: "Path to exposes.js"
    default: "./exposes.js"
  config:
    description: "Path to webpack.config.js"
    default: "./webpack.config.js"
outputs:
  path0:
    description: "The path of the build"
  path1:
    description: "The path of the build"

runs:
  using: "node12"
  main: "dist/action.js"
