name: CI
on: push

jobs:
  test:
    if: ${{ !env.ACT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Local action test
        id: container
        uses: ./
        with:
          exposes: "test/exposes.js"

      - run: echo ${{ steps.container.outputs.path }}
