name: Deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12"
        if: ${{ !env.ACT }}

      - run: |
          cd test
          yarn
        if: ${{ !env.ACT }}

        - run: |
          cd test
          yarn build:lambda
        if: ${{ !env.ACT }}

      - name: Local action test
        if: ${{ !env.ACT }}
        id: container
        uses: ./
        with:
          config: "test/webpack.config.js"
          exposes: "test/exposes.js"
          shared: "test/shared.js"

      - run: echo ${{ steps.container.outputs.path0 }}
        if: ${{ !env.ACT }}
      - run: ls -lh ${{ steps.container.outputs.path0 }}
        if: ${{ !env.ACT }}

      - name: Vercel Deployment
        if: ${{ !env.ACT }}
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: ./