name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ env.ACT }}
        uses: actions/checkout@v2
        with:
          path: "federated-container-action"

      - uses: actions/setup-node@v2
        with:
          node-version: "12"
        if: ${{ env.ACT }}

      - run: |
          cd federated-container-action/test
          yarn
        if: ${{ env.ACT }}

      - run: |
          cd federated-container-action/test
          yarn build:lambda
        if: ${{ env.ACT }}

      - name: Local action test
        if: ${{ env.ACT }}
        id: container
        uses: ./
        with:
          config: "federated-container-action/test/webpack.config.js"
          exposes: "federated-container-action/test/exposes.js"
          shared: "federated-container-action/test/shared.js"

      - run: echo ${{ steps.container.outputs.path0 }}
        if: ${{ env.ACT }}
      - run: ls -lh ${{ steps.container.outputs.path0 }}
        if: ${{ env.ACT }}
