name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "federated-container-action"
        if: ${{ env.ACT }}

      - name: Local action test
        if: ${{ env.ACT }}
        id: container
        uses: ./
        with:
          exposes: "federated-container-action/test/exposes.js"

      - run: echo ${{ steps.container.outputs.path }}
        if: ${{ env.ACT }}
